config/routes.rb
Rails.application.routes.draw do
  root 'lolzero/skill_guess#index'
  devise_for :users
  resources :games
  resources :matches
  resources :skills
  resources :champs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/champ.rb
class Champ < ApplicationRecord
  has_many :skills
end

app/controllers/champs_controller.rb
class ChampsController < ApplicationController
  before_action :set_champ, only: [:show, :edit, :update, :destroy]

  # GET /champs
  # GET /champs.json
  def index
    @champs = Champ.all
  end

  # GET /champs/1
  # GET /champs/1.json
  def show
  end

  # GET /champs/new
  def new
    @champ = Champ.new
  end

  # GET /champs/1/edit
  def edit
  end

  # POST /champs
  # POST /champs.json
  def create
    @champ = Champ.new(champ_params)

    respond_to do |format|
      if @champ.save
        format.html { redirect_to @champ, notice: 'Champ was successfully created.' }
        format.json { render :show, status: :created, location: @champ }
      else
        format.html { render :new }
        format.json { render json: @champ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champs/1
  # PATCH/PUT /champs/1.json
  def update
    respond_to do |format|
      if @champ.update(champ_params)
        format.html { redirect_to @champ, notice: 'Champ was successfully updated.' }
        format.json { render :show, status: :ok, location: @champ }
      else
        format.html { render :edit }
        format.json { render json: @champ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champs/1
  # DELETE /champs/1.json
  def destroy
    @champ.destroy
    respond_to do |format|
      format.html { redirect_to champs_url, notice: 'Champ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champ
      @champ = Champ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champ_params
      params.require(:champ).permit(:name, :description, :image_url)
    end
end

app/helpers/champs_helper.rb
module ChampsHelper
end

app/views/champs/_form.html.haml
= simple_form_for @champ, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.input :description
  = f.error_span :description
  = f.input :image_url
  = f.error_span :image_url
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), champs_path, :class => 'btn btn-default'

app/views/champs/edit.html.haml
- model_class = Champ
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/champs/index.html.haml
- model_class = Champ
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:image_url)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @champs.each do |champ|
      %tr
        %td= link_to champ.id, champ_path(champ)
        %td= champ.name
        %td= champ.description
        %td= champ.image_url
        %td=l champ.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_champ_path(champ), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), champ_path(champ), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_champ_path, :class => 'btn btn-primary'

app/views/champs/new.html.haml
- model_class = Champ
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/champs/show.html.haml
- model_class = Champ
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @champ.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @champ.description
%p
  %strong= model_class.human_attribute_name(:image_url) + ':'
  %br
  = @champ.image_url


= link_to t('.back', :default => t("helpers.links.back")), champs_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_champ_path(@champ), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), champ_path(@champ), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'