config/routes.rb
Rails.application.routes.draw do
  root 'lolzero/skill_guess#index'
  devise_for :users
  resources :games
  resources :matches
  resources :skills
  resources :champs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :champ
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :key, :image_url, :champ_id)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.haml
= simple_form_for @skill, :html => { :class => 'form-horizontal' } do |f|
  = f.input :image_url
  = f.error_span :image_url
  = f.input :name
  = f.error_span :name
  = f.input :key
  = f.error_span :key
  = f.association :champ
  = f.error_span :champ
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), skills_path, :class => 'btn btn-default'

app/views/skills/edit.html.haml
- model_class = Skill
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/skills/index.html.haml
- model_class = Skill
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:image_url)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:key)
      %th= model_class.human_attribute_name(:champ_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @skills.each do |skill|
      %tr
        %td= link_to skill.id, skill_path(skill)
        %td= skill.image_url
        %td= skill.name
        %td= skill.key
        %td= skill.champ_id
        %td=l skill.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_skill_path(skill), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), skill_path(skill), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_skill_path, :class => 'btn btn-primary'

app/views/skills/new.html.haml
- model_class = Skill
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/skills/show.html.haml
- model_class = Skill
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:image_url) + ':'
  %br
  = @skill.image_url
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @skill.name
%p
  %strong= model_class.human_attribute_name(:key) + ':'
  %br
  = @skill.key
%p
  %strong= model_class.human_attribute_name(:champ_id) + ':'
  %br
  = @skill.champ_id


= link_to t('.back', :default => t("helpers.links.back")), skills_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_skill_path(@skill), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), skill_path(@skill), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'