config/routes.rb
Rails.application.routes.draw do
  root 'lolzero/skill_guess#index'
  devise_for :users
  resources :games
  resources :matches
  resources :skills
  resources :champs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  validates :name, presence: true

  has_many :matches
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :description)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= simple_form_for @game, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.input :description
  = f.error_span :description
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), games_path, :class => 'btn btn-default'

app/views/games/edit.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/games/index.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @games.each do |game|
      %tr
        %td= link_to game.id, game_path(game)
        %td= game.name
        %td= game.description
        %td=l game.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_game_path(game), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), game_path(game), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_game_path, :class => 'btn btn-primary'

app/views/games/new.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/games/show.html.haml
- model_class = Game
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @game.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @game.description


= link_to t('.back', :default => t("helpers.links.back")), games_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_game_path(@game), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), game_path(@game), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'