config/routes.rb
Rails.application.routes.draw do
  root 'lolzero/skill_guess#index'
  devise_for :users
  resources :games
  resources :matches
  resources :skills
  resources :champs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  validates :score, presence: true

  belongs_to :game
  belongs_to :champ
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def match_params
    params.require(:match).permit(:score)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.haml
= simple_form_for @match, :html => { :class => 'form-horizontal' } do |f|
  = f.input :score
  = f.error_span :score
  = f.input :champ_id
  = f.error_span :champ_id
  = f.input :game_id
  = f.error_span :game_id
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), matches_path, :class => 'btn btn-default'

app/views/matches/edit.html.haml
- model_class = Match
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/matches/index.html.haml
- model_class = Match
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:score)
      %th= model_class.human_attribute_name(:champ_id)
      %th= model_class.human_attribute_name(:game_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @matches.each do |match|
      %tr
        %td= link_to match.id, match_path(match)
        %td= match.score
        %td= match.champ_id
        %td= match.game_id
        %td=l match.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_match_path(match), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), match_path(match), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_match_path, :class => 'btn btn-primary'

app/views/matches/new.html.haml
- model_class = Match
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/matches/show.html.haml
- model_class = Match
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:score) + ':'
  %br
  = @match.score
%p
  %strong= model_class.human_attribute_name(:champ_id) + ':'
  %br
  = @match.champ_id
%p
  %strong= model_class.human_attribute_name(:game_id) + ':'
  %br
  = @match.game_id


= link_to t('.back', :default => t("helpers.links.back")), matches_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_match_path(@match), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), match_path(@match), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'